### ISSUE TITLE
Script changed

### ISSUE THREAD

**Issue by AJCADamen** [xander1998/k9#1]
Hey @xander1998 
I fixed your script so it now attacks peds as well as players. Because I saw a lot of people wanted that to be a functionality. 
With your permission I would like to publish it. Whit you in the credits ofcourse.

**Comment by jeffreyvels** [comment]
can you share it with me? 
my e-mail is jvels16@gmail.com

**Comment by xander1998** [comment]
@jeffreyvels huh?

**Comment by LethalKingz** [comment]
@xander1998 I’ve been lurking for a bit, do you have any intention on finishing this or is it just a project? Otherwise I might look into finishing it off myself

**Comment by xander1998** [comment]
@LethalKingz this resource is the new one I was working on. I am a very busy person when it comes to life stuff plus other projects.

This resource also uses my xmenu repository resource if you wanna try this one out.
