### ISSUE TITLE
nothink work 

### ISSUE THREAD

**Issue by cedricalpatch** [xander1998/k9#3]
I have same issue, nothink work with alt and z or alt+z same time, I have warmenu named /resources/warmenu and k9 named /resources/k9 but nothink work, not blip on the map I try all in false in config and still same issue!?

**Comment by xander1998** [comment]
That really makes no sense.. Everyone else has it working.

**Comment by xander1998** [comment]
did you start the war menu before k9 and did you start the k9..

**Comment by cedricalpatch** [comment]
yes I have see on fivem the resently problem and this same for me... I have warmenu before k9 and of course I start the k9... I dont understand this great script but no work for me..

**Comment by cedricalpatch** [comment]
but not just after the warmenu, some line after... You think is problem?

**Comment by xander1998** [comment]
Say again? I didnt understand your last comment?

**Comment by cedricalpatch** [comment]
Sorry im french... The warmenu in server.cfg is before k9 but not just after, some line after. I have other start between tow

**Comment by xander1998** [comment]
That should be fine. Do you see any errors on the server or client console.

**Comment by cedricalpatch** [comment]
not any error... And the K9 blip not spawn also!?

**Comment by xander1998** [comment]
K9 has to be spawned for the blip to spawn.

**Comment by cedricalpatch** [comment]
I have the good message in consol when I start my server

**Comment by xander1998** [comment]
Yeah, that's just my version checker.

**Comment by cedricalpatch** [comment]
oh ok for blip

**Comment by cedricalpatch** [comment]
yes I know... So you have found the problem for 'bladehype911' in fivem?
I think is same like me?

**Comment by xander1998** [comment]
He was saying to make sure to load the warmenu before the K9 he didnt have anything wrong.

**Comment by xander1998** [comment]
Maybe send some screenshots of how you have it installed.

**Comment by cedricalpatch** [comment]
ok I make it

**Comment by xander1998** [comment]
I don't believe there is anything wrong with Tyne script as I have just reinstalled it on my test server and it works fine. Take the rest of your issue to the k9 topic in the fivem forums.

**Comment by cedricalpatch** [comment]
I use esx gamemode so this problem....
