### ISSUE TITLE
unstable syncing

### ISSUE THREAD

**Issue by Harmarz** [xander1998/k9#4]
It would appear dogs will de-sync for players around you sometimes they will not show.

**Comment by xander1998** [comment]
Nothing I can really do about that. Usually always a network issue.

**Comment by Harmarz** [comment]
believe i may have got a fix, last 1/2 hour it has been rendering for everyone 
https://pastebin.com/YFZK0t64


EndTextCommandSetBlipName(blip)
SetEntityAsMissionEntity(current_dog, true, false) -- added
if data.godmode == true then

**Comment by xander1998** [comment]
What exactly did you do add SetEntityAsMissionEntity before if data.godmode == true then

**Comment by Harmarz** [comment]
placed SetEntityAsMissionEntity within the frame of being spawned, the way it is now SetEntityAsMissionEntity is triggered when its deleted by the looks of it

**Comment by xander1998** [comment]
i know that. I do that so i can delete the entity. i just networked the entity. may be fine now.
