### ISSUE TITLE
Buggy

### ISSUE THREAD

**Issue by xAn-s** [xander1998/k9#6]
Alright, tried this out today. The "G" following action is almost impossible to get work properly, makes the script kinda useless never the less it is a super cool feature and would love to see a non buggy one but guess its kinda impossible to work with AI:s without problems.

**Comment by xander1998** [comment]
unless someone can tell me what i am doing wrong to fix it i cant really change it. until then just gotta wait til i figure it out.

**Comment by xAn-s** [comment]
I understand, anyways it is a great idea.
